//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3110Сотрудники
    {
        public int id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int ПаспортныеДанные { get; set; }
        public System.DateTime ДатаПриемаНаРаботу { get; set; }
        public string Квалификация { get; set; }
        public string Должность { get; set; }
        public string Образование { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual C3110Клиенты C3110Клиенты { get; set; }
    }
}
