//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user260_dbEntities : DbContext
    {
        public user260_dbEntities()
            : base("name=user260_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C3110ДанныеОПрограммах> C3110ДанныеОПрограммах { get; set; }
        public virtual DbSet<C3110Клиенты> C3110Клиенты { get; set; }
        public virtual DbSet<C3110Поставщики> C3110Поставщики { get; set; }
        public virtual DbSet<C3110Сотрудники> C3110Сотрудники { get; set; }
    }
}
